services:
  media-stream:
    image: luizmz94/tg-filestream-bot:latest
    container_name: media_stream_new
    restart: unless-stopped
    env_file:
      - stack.env
    ports:
      - 127.0.0.1:8001:8000
    networks:
      - mediatg

networks:
  mediatg:
    external: true
